Repository googleapis/nodejs-dialogflow, pull requests merged in 2019-05, with the labels that each got.

#327 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#328 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#329 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#331 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#332 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#315 feat: add the `updateDocument and `reloadDocument` methods
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/test.bat
  protos/google/cloud/dialogflow/v2/audio_config.proto
  protos/google/cloud/dialogflow/v2/session.proto
  protos/google/cloud/dialogflow/v2beta1/audio_config.proto
  src/v2/contexts_client.js
  src/v2/doc/google/cloud/dialogflow/v2/doc_audio_config.js
  src/v2/doc/google/cloud/dialogflow/v2/doc_session.js
  src/v2/doc/google/protobuf/doc_any.js
  src/v2/doc/google/protobuf/doc_field_mask.js
  src/v2/entity_types_client.js
  src/v2/intents_client.js
  src/v2beta1/contexts_client.js
  src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_audio_config.js
  src/v2beta1/doc/google/protobuf/doc_any.js
  src/v2beta1/doc/google/protobuf/doc_field_mask.js
  src/v2beta1/documents_client.js
  src/v2beta1/documents_client_config.json
  src/v2beta1/entity_types_client.js
  src/v2beta1/intents_client.js
  src/v2beta1/knowledge_bases_client.js
  src/v2beta1/knowledge_bases_client_config.json
  src/v2beta1/session_entity_types_client.js
  src/v2beta1/sessions_client.js
  synth.metadata
  test/gapic-v2beta1.js
Labels: cla: yes

#337 chore: release 0.9.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#339 fix: remove DEADLINE_EXCEEDED from list of idempotent operations
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/lint.sh
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/samples-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  src/v2/agents_client_config.json
  src/v2/contexts_client_config.json
  src/v2/entity_types_client_config.json
  src/v2/intents_client_config.json
  src/v2/session_entity_types_client_config.json
  src/v2/sessions_client_config.json
  src/v2beta1/agents_client_config.json
  src/v2beta1/contexts_client_config.json
  src/v2beta1/documents_client_config.json
  src/v2beta1/entity_types_client_config.json
  src/v2beta1/intents_client_config.json
  src/v2beta1/knowledge_bases_client_config.json
  src/v2beta1/session_entity_types_client_config.json
  src/v2beta1/sessions_client_config.json
  synth.metadata
Labels: cla: yes

#343 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v2/agents_client_config.json
  src/v2/contexts_client_config.json
  src/v2/entity_types_client_config.json
  src/v2/intents_client_config.json
  src/v2/session_entity_types_client_config.json
  src/v2/sessions_client_config.json
  src/v2beta1/agents_client_config.json
  src/v2beta1/contexts_client_config.json
  src/v2beta1/documents_client_config.json
  src/v2beta1/entity_types_client_config.json
  src/v2beta1/intents_client_config.json
  src/v2beta1/knowledge_bases_client_config.json
  src/v2beta1/session_entity_types_client_config.json
  src/v2beta1/sessions_client_config.json
  synth.metadata
Labels: cla: yes

#344 docs(samples): fix description typo
  samples/README.md
  samples/detect.v2beta1.js
Labels: cla: yes

#347 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#351 chore: release 0.9.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#353 TTS / Sentiment GA (handoff from Nirupa)
  samples/detect-intent-TTS-response.v2.js
  samples/detect-intent-sentiment.v2.js
  samples/system-test/detect.test.js
Labels: cla: yes

#355 refactor: drop dependency on lodash.merge and update links
  package.json
  protos/google/cloud/dialogflow/v2/agent.proto
  protos/google/cloud/dialogflow/v2/context.proto
  protos/google/cloud/dialogflow/v2/entity_type.proto
  protos/google/cloud/dialogflow/v2/intent.proto
  protos/google/cloud/dialogflow/v2/session.proto
  protos/google/cloud/dialogflow/v2/session_entity_type.proto
  protos/google/cloud/dialogflow/v2beta1/agent.proto
  protos/google/cloud/dialogflow/v2beta1/context.proto
  protos/google/cloud/dialogflow/v2beta1/document.proto
  protos/google/cloud/dialogflow/v2beta1/entity_type.proto
  protos/google/cloud/dialogflow/v2beta1/intent.proto
  protos/google/cloud/dialogflow/v2beta1/knowledge_base.proto
  protos/google/cloud/dialogflow/v2beta1/session.proto
  protos/google/cloud/dialogflow/v2beta1/session_entity_type.proto
  src/v2/agents_client.js
  src/v2/contexts_client.js
  src/v2/doc/google/cloud/dialogflow/v2/doc_intent.js
  src/v2/doc/google/cloud/dialogflow/v2/doc_session.js
  src/v2/entity_types_client.js
  src/v2/intents_client.js
  src/v2/session_entity_types_client.js
  src/v2/sessions_client.js
  src/v2beta1/agents_client.js
  src/v2beta1/contexts_client.js
  src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_document.js
  src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_intent.js
  src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_knowledge_base.js
  src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session.js
  src/v2beta1/documents_client.js
  src/v2beta1/entity_types_client.js
  src/v2beta1/intents_client.js
  src/v2beta1/knowledge_bases_client.js
  src/v2beta1/session_entity_types_client.js
  src/v2beta1/sessions_client.js
  synth.metadata
Labels: cla: yes

#356 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#357 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#359 chore: add .repo-metadata.json
  .repo-metadata.json
  synth.py
Labels: cla: yes

#360 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#361 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
