Repository googleapis/nodejs-dialogflow, pull requests merged in 2019-07, with the labels that each got.

#376 chore: release 0.10.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#372 refactor: replace `execa` with `execSync` in sample tests
  samples/package.json
  samples/system-test/detect.test.js
  samples/system-test/detect.v2beta1.test.js
  samples/system-test/resource.test.js
Labels: automerge, cla: yes

#383 chore: run the formatter
  samples/detect.v2beta1.js
  samples/system-test/detect.test.js
  samples/system-test/detect.v2beta1.test.js
  samples/system-test/resource.test.js
Labels: cla: yes

#388 fix(deps): drop dependency on through2
  package.json
  samples/detect.js
  samples/package.json
  test/gapic-v2.js
  test/gapic-v2beta1.js
Labels: cla: yes

#389 chore: release 0.10.3
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#396 docs: use the jsdoc-fresh theme
  .jsdoc.js
  package.json
Labels: cla: yes

#398 docs: document apiEndpoint over servicePath
  src/v2/agents_client.js
  src/v2/contexts_client.js
  src/v2/entity_types_client.js
  src/v2/intents_client.js
  src/v2/session_entity_types_client.js
  src/v2/sessions_client.js
  src/v2beta1/agents_client.js
  src/v2beta1/contexts_client.js
  src/v2beta1/documents_client.js
  src/v2beta1/entity_types_client.js
  src/v2beta1/intents_client.js
  src/v2beta1/knowledge_bases_client.js
  src/v2beta1/session_entity_types_client.js
  src/v2beta1/sessions_client.js
Labels: cla: yes
