Repository googleapis/nodejs-dialogflow, pull requests merged in 2020-09, with the labels that each got.

#679 build: update config for node12
  .github/publish.yml
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  samples/detect.js
  samples/detect.v2beta1.js
  samples/system-test/create-document.v2beta1.test.js
  samples/system-test/create-knowledge-base.v2beta1.test.js
  synth.metadata
Labels: cla: yes

#681 build: update to latest test config
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: cla: yes, context: none

#682 chore: update webhook proto
  protos/google/cloud/dialogflow/v2/webhook.proto
  synth.metadata
Labels: cla: yes, context: partial

#686 docs: update OPTIONAL annotations for some fields.
  protos/google/cloud/dialogflow/v2beta1/knowledge_base.proto
  protos/google/cloud/dialogflow/v2beta1/session.proto
  protos/protos.json
  src/v2beta1/knowledge_bases_client.ts
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full
