Repository googleapis/nodejs-dialogflow, pull requests merged in 2020-11, with the labels that each got.

#704 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#710 docs: note about metadata
  protos/google/cloud/dialogflow/v2beta1/document.proto
  src/v2beta1/documents_client.ts
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#703 fix!: removed ImportAgentResponse which was not ready for use yet. docs: minor doc changes
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full, do not merge

#718 fix(browser): check for fetch on window
  protos/protos.json
  src/v2/agents_client.ts
  src/v2/contexts_client.ts
  src/v2/entity_types_client.ts
  src/v2/environments_client.ts
  src/v2/intents_client.ts
  src/v2/session_entity_types_client.ts
  src/v2/sessions_client.ts
  src/v2beta1/agents_client.ts
  src/v2beta1/contexts_client.ts
  src/v2beta1/documents_client.ts
  src/v2beta1/entity_types_client.ts
  src/v2beta1/environments_client.ts
  src/v2beta1/intents_client.ts
  src/v2beta1/knowledge_bases_client.ts
  src/v2beta1/session_entity_types_client.ts
  src/v2beta1/sessions_client.ts
  synth.metadata
Labels: api: dialogflow, cla: yes, context: partial

#719 build: stop tracking generated files
  src/v2beta1/session_entity_types_client.ts
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#721 docs: fix npm package name in README
  .repo-metadata.json
  README.md
Labels: api: dialogflow, cla: yes
