Repository googleapis/nodejs-dialogflow, pull requests merged in 2020-07, with the labels that each got.

#632 chore: fix client library environment resource annotation.
  protos/google/cloud/dialogflow/v2beta1/environment.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full

#634 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#635 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#636 feat: adds projectAgentEnvironmentPathTemplate and projectAgentEnvironmentUserSessionContextPathTemplate
  protos/google/cloud/dialogflow/v2beta1/environment.proto
  protos/protos.json
  src/v2beta1/agents_client.ts
  src/v2beta1/contexts_client.ts
  src/v2beta1/documents_client.ts
  src/v2beta1/entity_types_client.ts
  src/v2beta1/environments_client.ts
  src/v2beta1/intents_client.ts
  src/v2beta1/knowledge_bases_client.ts
  src/v2beta1/session_entity_types_client.ts
  src/v2beta1/sessions_client.ts
  synth.metadata
  test/gapic_agents_v2beta1.ts
  test/gapic_contexts_v2beta1.ts
  test/gapic_documents_v2beta1.ts
  test/gapic_entity_types_v2beta1.ts
  test/gapic_environments_v2beta1.ts
  test/gapic_intents_v2beta1.ts
  test/gapic_knowledge_bases_v2beta1.ts
  test/gapic_session_entity_types_v2beta1.ts
  test/gapic_sessions_v2beta1.ts
Labels: cla: yes, context: none

#639 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#643 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#645 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#650 docs: more detailed docs on APIs such as Environment, and deleting Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/google/cloud/dialogflow/v2beta1/agent.proto
  protos/google/cloud/dialogflow/v2beta1/context.proto
  protos/google/cloud/dialogflow/v2beta1/document.proto
  protos/google/cloud/dialogflow/v2beta1/entity_type.proto
  protos/google/cloud/dialogflow/v2beta1/environment.proto
  protos/google/cloud/dialogflow/v2beta1/intent.proto
  protos/google/cloud/dialogflow/v2beta1/knowledge_base.proto
  protos/google/cloud/dialogflow/v2beta1/session.proto
  protos/google/cloud/dialogflow/v2beta1/session_entity_type.proto
  protos/protos.json
  src/v2beta1/agents_client.ts
  src/v2beta1/contexts_client.ts
  src/v2beta1/documents_client.ts
  src/v2beta1/entity_types_client.ts
  src/v2beta1/environments_client.ts
  src/v2beta1/intents_client.ts
  src/v2beta1/knowledge_bases_client.ts
  src/v2beta1/session_entity_types_client.ts
  src/v2beta1/sessions_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#651 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#652 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#654 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#653 fix: publish missing client config annotations
  protos/google/cloud/dialogflow/v2beta1/agent.proto
  protos/google/cloud/dialogflow/v2beta1/context.proto
  protos/google/cloud/dialogflow/v2beta1/document.proto
  protos/google/cloud/dialogflow/v2beta1/entity_type.proto
  protos/google/cloud/dialogflow/v2beta1/environment.proto
  protos/google/cloud/dialogflow/v2beta1/intent.proto
  protos/google/cloud/dialogflow/v2beta1/knowledge_base.proto
  protos/google/cloud/dialogflow/v2beta1/session.proto
  protos/google/cloud/dialogflow/v2beta1/session_entity_type.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full

#657 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#658 docs: more detailed docs on APIs such as Environment, Intents, Sessions.
  protos/google/cloud/dialogflow/v2/agent.proto
  protos/google/cloud/dialogflow/v2/context.proto
  protos/google/cloud/dialogflow/v2/entity_type.proto
  protos/google/cloud/dialogflow/v2/environment.proto
  protos/google/cloud/dialogflow/v2/intent.proto
  protos/google/cloud/dialogflow/v2/session.proto
  protos/google/cloud/dialogflow/v2/session_entity_type.proto
  src/v2/contexts_client.ts
  src/v2/entity_types_client.ts
  src/v2/environments_client.ts
  src/v2/intents_client.ts
  src/v2/session_entity_types_client.ts
  src/v2/sessions_client.ts
  synth.metadata
Labels: cla: yes, context: full

#662 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
