Repository googleapis/nodejs-dialogflow, pull requests merged in 2020-05, with the labels that each got.

#606 feat: check status of long running operation by its name
  src/v2/agents_client.ts
  src/v2/entity_types_client.ts
  src/v2/intents_client.ts
  synth.metadata
  test/gapic_agents_v2.ts
  test/gapic_contexts_v2.ts
  test/gapic_entity_types_v2.ts
  test/gapic_environments_v2.ts
  test/gapic_intents_v2.ts
  test/gapic_session_entity_types_v2.ts
  test/gapic_sessions_v2.ts
Labels: automerge, cla: yes

#608 chore: linting rules
  protos/google/cloud/dialogflow/v2/audio_config.proto
  synth.metadata
Labels: automerge, cla: yes, context: none

#610 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#615 fix: exception occurred in retry method
  package.json
Labels: cla: yes
